export const STATUSES = [
  { label: 'Aktivní', value: 'Active' },
  { label: 'Smazáno', value: 'Deleted' },
];

export const COMPANY_BUSINESS_TYPES = [
  '',
  'Analytik',
  'Konkurent',
  'Zákazník',
  'Integrátor',
  'Investor',
  'Partner',
  'Noviny',
  'Vyhlídka',
  'Překupník',
  'Jiný',
];

export const DEFAULT_COMPANY_INDUSTRY_TYPES = [
  '',
  'Letectví a Obrana',
  'Letecká přeprava a Logistika',
  'Aerolinie',
  'Auto Komponenty',
  'Automobily',
  'Banky',
  'Nápoje',
  'Biotechnologie',
  'Stavební Produkty',
  'Kapitálové Trhy',
  'Chemikálie',
  'Komerční Služby a Dodávky',
  'Komunikační Zařízení',
  'Stavební Inženýrství',
  'Konstrukční Materiály',
  'Spotřebitelské Finance',
  'Kontejnery a Obaly',
  'Distributoři',
  'Diverzifikované Spotřebitelské Služby',
  'Diverzifikované Finanční Služby',
  'Diversified Telecommunication Services',
  'Elektrické Služby',
  'Elektrické Zařízení',
  'Elektronická Zařízení, Nástroje a Komponenty',
  'Energetická Zařízení a Služby',
  'Zábava',
  'Akciové Investiční Fondy do Nemovitostí (REIT)',
  'Maloobchod s Potravinami a Základními Potravinami',
  'Potravinářské Výrobky',
  'Plynové Služby',
  'Vybavení a Potřeby pro Zdravotní Péči',
  'Poskytovatelé Zdravotní Péče a Služby',
  'Technologie Zdravotní Péče',
  'Hotely, Restaurace a Volný čas',
  'Zboží Dlouhodobé Spotřeby',
  'Výrobky pro Domácnost',
  'Nezávislí Výrobci Elektřiny a Elektřiny z Obnovitelných Zdrojů',
  'Průmyslové Konglomeráty',
  'Pojištění',
  'Interaktivní Média a Služby',
  'Internet a Přímý Marketing Maloobchod',
  'IT služby',
  'Produkty pro Volný čas',
  'Nástroje a Služby pro Vědy o živé Přírodě',
  'Stroje',
  'Námořní',
  'Média',
  'Kovy a Těžba',
  'Hypoteční Investiční Fondy do Nemovitostí (REIT)',
  'Multi-Utilities',
  'Multiline Maloobchod',
  'Ropa, Plyn a Spotřební Paliva',
  'Papír a Lesní Produkty',
  'Osobní Produkty',
  'Léčiva',
  'Profesionální Služby',
  'Správa a Rozvoj Nemovitostí',
  'Silnice a železnice',
  'Polovodiče a Polovodičová Zařízení',
  'Software',
  'Specializovaný Maloobchod',
  'Technologie Hardware, úložiště a Periferní Zařízení',
  'Textil, Oděvy a luxusní zboží',
  'Spořivosti a Financování Hypoték',
  'Tabák',
  'Obchodní Společnosti a Distributoři',
  'Dopravní Infrastruktura',
  'Vodní Služby',
  'Bezdrátové Telekomunikační Služby',
  'Přeprava',
  'Hornictví',
  'Finance',
  'Společnost skupiny',
  'Vláda',
  'Užitek',
  'Vzdělání',
  'Výrobní',
  'Sdělení',
  'Maloobchodní',
  'Zdraví',
  'Konstrukce',
  'Řízení',
];

export const COMPANY_INDUSTRY_TYPES = [...DEFAULT_COMPANY_INDUSTRY_TYPES];

export const DEFAULT_SOCIAL_LINKS = [
  { label: 'Facebook', value: 'facebook' },
  { label: 'Twitter', value: 'twitter' },
  { label: 'Youtube', value: 'youtube' },
  { label: 'Website', value: 'website' },
];

export const SOCIAL_LINKS = [
  ...DEFAULT_SOCIAL_LINKS,
  { label: 'Academia.edu', value: 'academia.edu' },
  { label: 'Chess.com', value: 'chess.com' },
  { label: 'Crunchyroll', value: 'crunchyroll' },
  { label: 'DeviantArt', value: 'deviantArt' },
  { label: 'Discord', value: 'discord' },
  { label: 'Douban', value: 'douban' },
  { label: 'eToro', value: 'eToro' },
  { label: 'Flickr', value: 'flickr' },
  { label: 'Gapo', value: 'gapo' },
  { label: 'Goodreads', value: 'goodreads' },
  { label: 'GitHub', value: 'gitHub' },
  { label: 'Instagram', value: 'instagram' },
  { label: 'KakaoStory', value: 'kakaoStory' },
  { label: 'KizlarSoruyor', value: 'kizlarSoruyor' },
  { label: 'Last.fm', value: 'last.fm' },
  { label: 'LinkedIn', value: 'linkedIn' },
  { label: 'LiveJournal', value: 'liveJournal' },
  { label: 'Pinterest', value: 'pinterest' },
  { label: 'Pixnet', value: 'pixnet' },
  { label: 'Plurk', value: 'plurk' },
  { label: 'Quora', value: 'quora' },
  { label: 'Reddit', value: 'reddit' },
  { label: 'Renren', value: 'renren' },
  { label: 'Sina Weibo', value: 'sinaWeibo' },
  { label: 'SoundCloud', value: 'soundCloud' },
  { label: 'Spotify', value: 'spotify' },
  { label: 'Steam', value: 'steam' },
  { label: 'Tagged', value: 'tagged' },
  { label: 'Taringa', value: 'taringa' },
  { label: 'Tumblr', value: 'tumblr' },
  { label: 'VK', value: 'vk' },
  { label: 'Voat', value: 'voat' },
  { label: 'Wattpad', value: 'wattpad' },
  { label: 'XING', value: 'xing' },
  { label: 'Yammer', value: 'yammer' },
  { label: 'Yelp', value: 'yelp' },
];

export const DEFAULT_SEX_CHOICES = [
  { label: 'Neznámý', value: 0 },
  { label: 'Mužský', value: 1 },
  { label: 'ženský', value: 2 },
  { label: 'Nelze použít', value: 9 },
];

export const SEX_OPTIONS = [
  ...DEFAULT_SEX_CHOICES,
  { label: 'co/co', value: 10 },
  { label: 'en/en', value: 11 },
  { label: 'ey/em', value: 12 },
  { label: 'on/jemu', value: 13 },
  { label: 'on/oni', value: 14 },
  { label: 'ona/ona', value: 15 },
  { label: 'ona/oni', value: 16 },
  { label: 'oni/jim', value: 17 },
  { label: 'xie/hir', value: 18 },
  { label: 'yo/yo', value: 19 },
  { label: 'ze/zir', value: 20 },
  { label: 've/vis', value: 21 },
  { label: 'xe/xem', value: 22 },
];

export const DEFAULT_CONSTANT_VALUES = {
  sex_choices: DEFAULT_SEX_CHOICES,
  company_industry_types: DEFAULT_COMPANY_INDUSTRY_TYPES.map((v) => ({
    label: v,
    value: v,
  })),
  social_links: DEFAULT_SOCIAL_LINKS,
};

export const USER_ROLES = {
  SYSTEM: 'systém',
  USER: 'uživatel',
  ALL: ['systém', 'uživatel'],
};
