name: SHQ WEB CI

on:
  push:
    branches:
      - dev
      - main
      - staging
      - shq-improve
    paths:
      - 'shq-web/**'
      - '.github/workflows/shq.yaml'

  pull_request:
    branches:
      - dev
      - main
      - staging
      - shq-improve
    paths:
      - 'shq-web/**'
      - '.github/workflows/shq.yaml'

jobs:
  shq-ui:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.17.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.x

      - name: Build
        run: |
          cd shq-web
          rm -rf node_modules
          yarn install --frozen-lockfile
          yarn build

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/shq-improve')
        run: |
          cd shq-web
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          DOCKER_BUILDKIT=1 docker build -t saashqdev/shq:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push saashqdev/shq:${GITHUB_REF#refs/heads/}
